name: Release Gateway

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Tag in your repo to copy (default: test)'
        required: true
        default: 'test'
      target_tag:
        description: 'Target tag to apply (default: latest)'
        required: false
        default: 'latest'

permissions:
  contents: read
  packages: write

env:
  REPO_NAME: documentdb-local

jobs:
  copy-and-push-manifest:
    strategy:
      matrix:
        pg_version:
          - 15
          - 16
          - 17
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Retag existing manifest
        env:
          SOURCE_TAG: ${{ github.event.inputs.source_tag }}
          TARGET_TAG: ${{ github.event.inputs.target_tag }}
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}/${{ env.REPO_NAME }}:${{ matrix.pg_version }} \
            ghcr.io/${{ github.repository }}/${{ env.REPO_NAME }}:${{ env.SOURCE_TAG }}-${{ matrix.pg_version }}

      - name: Retag existing manifest (latest)
        if: ${{ matrix.pg_version == '17' }}
        env:
          SOURCE_TAG: ${{ github.event.inputs.source_tag }}
          TARGET_TAG: ${{ github.event.inputs.target_tag }}
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}/${{ env.REPO_NAME }}:latest \
            ghcr.io/${{ github.repository }}/${{ env.REPO_NAME }}:${{ env.SOURCE_TAG }}-17
